version: 2.1

jobs:
  Hello-World:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: The first step
          command: |
            echo 'Hello World'
            echo 'This is a delivery pipe'
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Getting Code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  Using-Node:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name: Running the Node Container
          command: node -v

workflows:
  Example-Workflow:
    jobs:
      - Hello-World
      - Fetch-Code:
          requires:
            - Hello-World
      - Using-Node:
          requires:
            - Fetch-Code
